/* Copyright(C) 2007 National Institute of Informatics, All rights reserved.*/
CREATE USER SA PASSWORD '' ADMIN;

DROP TABLE PAYMENT      IF EXISTS;
DROP TABLE AVAILABLEQTY IF EXISTS;
DROP TABLE RESERVATION  IF EXISTS;
DROP TABLE ROOM         IF EXISTS;

CREATE TABLE PAYMENT (
  ROOMNUMBER   VARCHAR(50) NOT NULL,
  STAYINGDATE  VARCHAR(20) NOT NULL,
  AMOUNT       INTEGER,
  STATUS       VARCHAR(10),
  CONSTRAINT PK_PAYMENT PRIMARY KEY (ROOMNUMBER, STAYINGDATE)
);

CREATE TABLE AVAILABLEQTY (
  DATE       VARCHAR(20) NOT NULL,
  ROOM_TYPE  VARCHAR(50) NOT NULL,
  QTY        INTEGER,
  CONSTRAINT PK_AVAILABLEQTY PRIMARY KEY (DATE, ROOM_TYPE)
);

-- ← ここだけ１回だけ！
CREATE TABLE RESERVATION (
  RESERVATIONNUMBER VARCHAR(50) NOT NULL PRIMARY KEY,
  STAYINGDATE       VARCHAR(20),
  STATUS            VARCHAR(10),
  ROOM_TYPE         VARCHAR(50),
  ROOM_COUNT        INTEGER
);

CREATE TABLE ROOM (
  ROOMNUMBER   VARCHAR(50) NOT NULL PRIMARY KEY,
  STAYINGDATE  VARCHAR(20)
);

-- 部屋の情報（5部屋分）
INSERT INTO ROOM VALUES('1001','');
INSERT INTO ROOM VALUES('1002','');
INSERT INTO ROOM VALUES('1003','');
INSERT INTO ROOM VALUES('1004','');
INSERT INTO ROOM VALUES('1005','');

-- 部屋タイプ別の在庫（例：2025/07/15）
INSERT INTO AVAILABLEQTY VALUES('2025/07/15', 'Single', 5);
INSERT INTO AVAILABLEQTY VALUES('2025/07/15', 'Double', 3);
